// 4
// X.........
// ..........
// .......X..
// .....X....
// ......X...
// ..........
// .........X
// ..X.......
// ..........
// .........X
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ..........
// ....X.....
// ..........
// ..........
// ..........
// ..........
// ..........
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX
// XXXXXXXXXX

//Logic - i determines the maximum possible score, and j determines the actual score attained.
#include<bits/stdc++.h>
using namespace std;
int main(){
    int t;
    cin>>t;
    while(t>0){
        vector<vector<char>> arr(10, vector<char> (10));
        for(int i =0; i<10; i++){
            for(int  j= 0; j<10; j++){
                cin>>arr[i][j];
            }
        }
        int score = 0;
        for(int i = 0; i<10; i++){
            for(int j = 0; j<10; j++){
                if(arr[i][j]=='X'){
                    int m_score = min(i+1, 10-i);
                    int k = j+1;
                    if(k>5){
                        k=11-k;
                    }
                    if(k>=m_score){
                            score+=m_score;
                        }
                        else{
                            score+=k;
                        }
                }
            }
        }
        cout<<score<<endl;
    terminateIteration: t--;
    }

    return 0;
}
